pipeline {
    agent any

    environment {
        CONTAINER_NAME = "gappa-back"
        IMAGE_NAME = "gappa"
    }
    stages {
        stage('Build') {
            steps {
                dir('BackEnd/gappa') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build'
//                    // 디버깅
//                    sh 'ls -al ./build'
//                    sh './gradlew build --stacktrace'
                }
            }
            post {
                success {
                    echo 'gradle build success'
                }

                failure {
                    echo 'gradle build failed'
                }
            }
        }

        stage('Docker Delete') {
            steps {
                script {
                    try{
                        sh 'echo "Docker Delete Start"'
                        // 컨테이너 존재 시 삭제
                        sh "docker stop ${CONTAINER_NAME}"
                        sh "docker rm -f ${CONTAINER_NAME}"
                    }catch (Exception e){
                        echo "Docker container ${CONTAINER_NAME} does not exist. skip"
                    }
                    try{
                        // 이미지 존재 시 삭제
                        sh "docker image rm ${IMAGE_NAME}"
                    }catch (Exception e){
                        echo "Docker image ${IMAGE_NAME} does not exist. skip"
                    }
                }
            }
            post {
                success {
                    sh 'echo "Docker delete Success"'
                }
                failure {
                    sh 'echo "Docker delete Fail"'
                }
            }
        }

        stage('Dockerizing'){
            steps{
                sh 'echo " Image Bulid Start"'
                // 도커 이미지를 기반으로 컨테이너 빌드
                dir('BackEnd/gappa') {
                    sh 'docker build -t ${IMAGE_NAME} .'
                }
            }
            post {
                success {
                    sh 'echo "Bulid Docker Image Success"'
                }

                failure {
                    sh 'echo "Bulid Docker Image Fail"'
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    sh 'docker run --name ${CONTAINER_NAME} -d -p 8080:8080 ${IMAGE_NAME}'
                }
            }
            post {
                success {
                    echo 'Deploy success'
                }
                failure {
                    echo 'Deploy failed'
                }
            }
        }
    }
}
